#!/bin/bash
echo "Atualizando ChatPlus, por favor aguarde."

git pull
cd backend
npm install
rm -rf dist
npm run build
npx sequelize db:migrate
npx sequelize db:seed
cd ../frontend
npm install
rm -rf build
npm run build
pm2 restart all

echo "Atualização finalizada. Aproveite!"
